version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.production
    container_name: proyecto_distribuidos
    env_file:
      - .env.production
    ports:
      - "3000:3000"