version: '3'

services:
  app:
    build: ./
    container_name: proyecto_distribuidos
    restart: on-failure
    entrypoint: /app/etc/entrypoint.sh
    volumes:
      - .:/app
      # - /app/node_modules
    ports:
      - "3000:3000"