FROM node:19.9.0-alpine3.17 as builder

WORKDIR /app

COPY ./ /app

RUN npm install

RUN npm run build-only

FROM nginx:alpine3.18 as production-stage

COPY --from=builder /app/dist /usr/share/nginx/html

COPY ./etc/nginx/default.conf /etc/nginx/conf.d

EXPOSE 3000

ENTRYPOINT ["nginx", "-g", "daemon off;"]